name: Prebuild Dev Container

on:
  push:
    branches:
      - main
    paths:
      - ".devcontainer/**"
      - "package.json"
      - "package-lock.json"
      - "sites/*/package.json"
  workflow_dispatch:

jobs:
  prebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          push: always
